#!/usr/bin/env python
"""Render today's Filter E recommendations as a phone-friendly HTML email + a
plain-text fallback. The email subject line is the first line of the .txt file
(picked up by the workflow's `digest.subject` step output).

Inputs:
    data/output/recommendations/{date}_filter_e.csv

Outputs:
    digest.html  — multipart/alternative HTML body
    digest.txt   — first line is the email Subject, remainder is the text body
"""
from __future__ import annotations

import argparse
import html
from datetime import date
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
RECS_DIR = REPO_ROOT / "data" / "output" / "recommendations"

# Columns to surface in the digest (in display order). Each entry is a list
# of acceptable source column names — recommend.py's CSV has merge-suffix
# leakage (`player_name_x`, `player_name_y`) and uses `opponent` instead of
# `opp_team`, so we resolve aliases at render time rather than relying on a
# pristine schema. The first matching alias wins; missing columns are
# silently skipped.
PREFERRED_COLS: list[tuple[str, list[str]]] = [
    ("player",        ["player_name", "player_name_x", "player_name_y"]),
    ("team",          ["team"]),
    ("opp",           ["opp_team", "opponent"]),
    ("H/A",           ["home_away"]),
    ("price",         ["over_price"]),
    ("p_model",       ["p_model"]),
    ("edge",          ["edge"]),
    ("platoon",       ["platoon_advantage"]),
    ("pitcher_known", ["pitcher_features_known"]),
    ("lineup",        ["lineup_confirmed"]),
    ("start_rate",    ["start_rate"]),
]


def _resolve_col(df: pd.DataFrame, aliases: list[str]) -> str | None:
    """Return the first alias that exists in df, or None."""
    for a in aliases:
        if a in df.columns:
            return a
    return None


def _format_value(display_col: str, val) -> str:
    """Format by DISPLAY column name (the user-facing label), not the source
    column name — keeps formatting independent of the alias-resolution layer.
    """
    if pd.isna(val):
        return ""
    if display_col in {"p_model", "edge", "start_rate"}:
        try:
            return f"{float(val) * 100:.1f}%"
        except (TypeError, ValueError):
            return str(val)
    if display_col == "price":
        try:
            v = int(val)
            return f"+{v}" if v > 0 else str(v)
        except (TypeError, ValueError):
            return str(val)
    if display_col in {"platoon", "pitcher_known"}:
        try:
            return "yes" if int(val) == 1 else "no"
        except (TypeError, ValueError):
            return str(val)
    if display_col == "lineup":
        # Boolean: True = MLB-confirmed, False = projected starter.
        try:
            return "confirmed" if bool(val) else "projected"
        except (TypeError, ValueError):
            return str(val)
    return str(val)


def _render_html(df: pd.DataFrame, target: str) -> str:
    # Resolve aliases once: list of (display_label, source_col) pairs.
    resolved: list[tuple[str, str]] = []
    for display, aliases in PREFERRED_COLS:
        src = _resolve_col(df, aliases)
        if src is not None:
            resolved.append((display, src))

    rows_html = []
    for _, row in df.iterrows():
        cells = "".join(
            f"<td>{html.escape(_format_value(display, row[src]))}</td>"
            for display, src in resolved
        )
        rows_html.append(f"<tr>{cells}</tr>")
    headers = "".join(f"<th>{html.escape(display)}</th>" for display, _ in resolved)

    n = len(df)
    avg_edge  = df["edge"].mean()       if "edge" in df.columns and n        else 0.0
    avg_price = df["over_price"].mean() if "over_price" in df.columns and n  else 0.0
    return f"""<!doctype html>
<html><body style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;color:#222;">
  <h2 style="margin:0 0 4px 0;">Filter E picks — {html.escape(target)}</h2>
  <p style="margin:0 0 16px 0;color:#555;">
    {n} bets · avg edge {avg_edge*100:.1f}% · avg price {avg_price:+.0f}
  </p>
  <table cellspacing="0" cellpadding="6"
         style="border-collapse:collapse;width:100%;font-size:14px;">
    <thead style="background:#f3f3f3;">
      <tr>{headers}</tr>
    </thead>
    <tbody>{''.join(rows_html)}</tbody>
  </table>
  <p style="margin-top:16px;color:#888;font-size:12px;">
    Auto-generated by the daily-picks workflow. Full CSV attached.
  </p>
</body></html>
"""


def _render_text(df: pd.DataFrame, target: str) -> str:
    n = len(df)
    avg_edge = df["edge"].mean() if "edge" in df.columns and n else 0.0
    subject = f"MLB picks {target}: {n} bets, avg edge {avg_edge*100:.1f}%"
    if df.empty:
        body = "No bets cleared Filter E today."
    else:
        # Compact text body — name, team, opponent, price, edge.
        text_cols: list[tuple[str, list[str]]] = [
            ("player", ["player_name", "player_name_x", "player_name_y"]),
            ("team",   ["team"]),
            ("opp",    ["opp_team", "opponent"]),
            ("price",  ["over_price"]),
            ("edge",   ["edge"]),
        ]
        resolved = [(d, _resolve_col(df, a)) for d, a in text_cols]
        resolved = [(d, s) for d, s in resolved if s is not None]
        body = "\n".join(
            "  " + "  ".join(_format_value(d, row[s]).ljust(14) for d, s in resolved)
            for _, row in df.iterrows()
        )
    return f"{subject}\n\n{body}\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", required=True, help="YYYY-MM-DD")
    parser.add_argument("--out", default="digest.html")
    parser.add_argument("--out-text", default="digest.txt")
    args = parser.parse_args()

    target = args.date
    # Validate format so a malformed --date doesn't silently produce empty output.
    date.fromisoformat(target)

    csv_path = RECS_DIR / f"{target}_filter_e.csv"
    if csv_path.exists():
        df = pd.read_csv(csv_path)
    else:
        print(f"  WARN: {csv_path} not found — emitting empty digest.")
        df = pd.DataFrame()

    Path(args.out).write_text(_render_html(df, target), encoding="utf-8")
    Path(args.out_text).write_text(_render_text(df, target), encoding="utf-8")
    print(f"  wrote {args.out} ({len(df)} rows) and {args.out_text}")


if __name__ == "__main__":
    main()
